services:

  bot:
    command: ["python", "src/main.py"]
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: bot_stankozavod:latest
    env_file:
      - .env